version: "2"
services:
  app.backend:
    container_name: app-backend
    build: .
    ports:
     - 4101:4101
    environment:
      - TZ=UTC
      - NODE_ENV
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    depends_on:
     - db

  db:
    image: app/db:dev
    build:
      context: ../db
    ports:
     - 5432:5432
    environment:
     - APP_PASS=password
